name: Tag Release

on:
  push:
    branches: ['master']
    paths-ignore: ['*.md']

jobs:
  tag:
    uses: start9labs/shared-workflows/.github/workflows/tagRelease.yml@master
    with:
      PROD_REGISTRY: ${{ vars.PROD_REGISTRY }}
    permissions:
      contents: write
